### ISSUE TITLE
Error when returning to callback

### ISSUE THREAD

**Issue by gagizagi** [yanatan16/passport-youtube-v3#10]
I have been trying to make this work but I keep getting this error after logging in to youtube and returning to callback route

`Error
    at C:\Users\GazZy\Desktop\passport\node_modules\passport-youtube-v3\lib\passport-youtube-v3\strategy.js:56:28
    at passBackControl (C:\Users\GazZy\Desktop\passport\node_modules\oauth\lib\oauth2.js:132:9)
    at IncomingMessage.<anonymous> (C:\Users\GazZy\Desktop\passport\node_modules\oauth\lib\oauth2.js:157:7)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)`

I started with the code in the readme, trying different things and ended up copying https://gist.github.com/bertrandmartel/51908fcd70872133ed83492b602cf94f just to see if that would work, but no luck

**Comment by gagizagi** [comment]
Didn't have the right google api enabled.
